language: python
dist: trusty

compiler:
  - gcc

os:
  - linux

env:
  global:
    - INSTALL_ROOT=$HOME/install

addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - libboost1.55-all-dev
      - liblapack-dev

sudo: required

python:
  - 2.7
  - 3.6

matrix:
    fast_finish: true

before_install:
  - export CXX="g++-4.9" CC="gcc-4.9"
  - export PYTHONPATH=$INSTALL_ROOT/lib/python$TRAVIS_PYTHON_VERSION/dist-packages:$PYTHONPATH


install:
  - pushd ..
  - git clone https://github.com/equinor/libecl.git
  - git clone --recursive https://github.com/OPM/opm-common.git
  - git clone --recursive https://github.com/equinor/sunbeam.git
  - pushd libecl
  - pip install -r requirements.txt
  - popd
  - mkdir libecl/build
  - pushd libecl/build
  - cmake .. -DENABLE_PYTHON=ON
             -DBUILD_TESTS=OFF
             -DCMAKE_INSTALL_PREFIX=$INSTALL_ROOT ..
  - make -j4 install
  - popd
  - mkdir opm-common/build
  - pushd opm-common/build
  - git checkout release/sunbeam/2019.02
  - cmake .. -DCMAKE_PREFIX_PATH=$INSTALL_ROOT
             -DCMAKE_INSTALL_PREFIX=$INSTALL_ROOT
             -DBUILD_TESTING=OFF
             -DBUILD_SHARED_LIBS=ON
  - make -j4 install
  - popd
  - mkdir sunbeam/build
  - pushd sunbeam/build
  - cmake .. -DCMAKE_PREFIX_PATH=$INSTALL_ROOT
             -DUSE_RPATH=ON
             -DCMAKE_INSTALL_PREFIX=$INSTALL_ROOT
             -DPYTHON_EXECUTABLE=`which python`
  - make -j 4 install
  - popd
  - popd
  - pip install -r requirements_dev.txt
  - pip install .

script:
  - pytest
  - make docsrun

deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: ./docs/_build/html
    github_token:
      secure: "IMfU+2qMvtSkN63mQ7W1/Ggdk0iDJERB8O8qAT6M2s9cKWGPjX1+atX2XBlGUFl3USLP+AqtOWdA8XcP0kHRTDRLITL4fin6gprPO4AVVIzNKfUrU3RtS3/IqKvQEd3QIsc9G5bIweWvjcTddytJrLbAZC2H4GzHusvp68321Owa50OfShka0qyZT/UyRVY09gz9XstNAvlh/9HQLn/uiuFeoKIzLmR9GgkkfwqLLX6NVp5q1zzL8iMM2ZVS9/VTBDyFUbqfzpRu7a1VsORaCbSvLSI96pm+SAdD6vuRjMNIEBB875TY/ZdnuRpSckTrpiN5ks9BoFRLBMJTNIEdl5zPRVKPZwIeu609w+Q1pKXzyeUc0j7zmjoBDAnhzpTxZd92XhW4oLcT3w3ZP6OMZqgYcxrOLj2Fj/4kIHhDq3iFMtWRio4mxZR5R1YkQMnIArmgiNEB/+XQGCxdwIyJvLc/mLv24e4pmFxArSCV4lIupIaZc2FqEi6RwMFkCw3q+YJ6a1Se0vaxx73h7+VuUDZxzhnO1PU9bQYmSmLbP7oGyD5KBKlOcMX/NC6eEXULhn3eVF3bEiwiVz9JYC834U+NWOyLzNBOrInEo98r9SFPb2Rp489bEHpEtinBqWfXQEjBaBknnMEp9NJrsWwppwwVKb06R+7OHWzWhscs7rQ="      
    keep_history: true
    on:
      branch: docdeploy
      python: "3.6"
